### ISSUE TITLE
Define different modules dependencies for tests only

### ISSUE THREAD

**Issue by fondasimone** [prezi/spaghetti#120]
It would be great to being able to define an explicit list of modules accessible to the test code only for a given module.

Use case: modA is exposing something coming from Bacon (like an Observable), modB is using that thing:  Bacon > modA > modB .

At the moment, to being able to use Bacon in modB's tests, you need to explicitly include bacon into modB dependencies, even if not needed at run time.

Having different confs for tests would allow the dependencies to remain "honest" and the tests to have access to whatever they need to create/trigger in order to do their job.

**Comment by lptr** [comment]
Going to be solved in #170.
