### ISSUE TITLE
Shadow external functionality when wrapping module code

### ISSUE THREAD

**Issue by lptr** [prezi/spaghetti#122]
Things like `require`, `define`, `__dirname` should not be available to the module to prevent module code relying on external services that are not available in different kinds of packaging.

**Comment by knuton** [comment]
I don't think there is a reasonable way to unset variables from an enclosing scope in a general way, and I am not really sure it is desirable.

The goal must be to unset any auxiliary variables used by Spaghetti by restoring them back to their value in the enclosing scope.

**Comment by knuton** [comment]
I looked at which of Spaghetti's auxiliary variables are currently leaked into the module implementations, and it is only `module`, the module constructor function.

This could be done away with by inlining the function definition, thereby getting rid of the `module` name altogether. I don't see a real need at the moment however, and won't address it for now.

Closing.
