### ISSUE TITLE
Consider using WebIDL

### ISSUE THREAD

**Issue by lptr** [prezi/spaghetti#68]
WebIDL could be another language (or the only language) to define Spaghetti interfaces. Or we could generate WebIDL from Spaghetti.

WebIDL is a more mature and standard solution than our own language, though it's geared towards JS <-> native (i.e. the browser) interactions. This might have benefits and drawbacks as well.

At first look it has all the features we need (annotations, ways to define interfaces and enums etc.), and some more stuff we don't need. The only significant difference seems to be how enums are handled: Spaghetti uses glorified `int`s, WebIDL uses strings.

**Comment by knuton** [comment]
No clear benefit to this right now.
