### ISSUE TITLE
Typescript: emulate mixins

### ISSUE THREAD

**Issue by Schipy** [prezi/spaghetti#99]
I would love to see a construct like this:

```
@mixin
string getFoo(BadAssMonkey monkey);

//in an other Spaghetti module
@mixin
string getBar(BadAssMonkey monkey, string someParam);
```

in Typescript getting translated to
```
interface BadAssMonkey {
    getFoo(): string;
}

interface BadAssMonkey {
    getBar(someParam:string): string;
}
```
since interface definitions are additive descriptions, this way new members can be mixed in to existing types

In Haxe the same getting translated to
```
public static function getFoo(monkey:BadAssMonkey);

public static function getBar(monkey:BadAssMonkey, someParam:string);
```

which can be used as mixin with the [using](http://old.haxe.org/manual/using) sytnax

**Comment by lptr** [comment]
There is the possibility now to create additional generators.
